# fly.toml app configuration file generated for cafecode-backend on 2025-08-19T18:58:19-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cafecode-backend'
primary_region = 'sjc'

[build]
  dockerfile = 'backend/Dockerfile'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-2x'
