# fly.toml app configuration file generated for cafecode-backend-v2 on 2025-08-19T19:30:49-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cafecode-backend-v2'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']
  
  # Health check endpoint
  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    timeout = "5s"
    method = "GET"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false


[[vm]]
  size = 'shared-cpu-2x'

# Environment variables
[env]
  NODE_ENV = "production"
